-- v0.28.0: columnas de tipo de factura y rectificativa en la tabla de registro.
-- Las crea script.php (postflight), porque la comprobación de existencia de una
-- columna no se puede escribir en SQL válido para MySQL y MariaDB a la vez.
